\copy guideline(name,url) from STDIN;
abacavir and HLA-B	https://cpicpgx.org/guidelines/guideline-for-abacavir-and-hla-b/
allopurinol and HLA-B	https://cpicpgx.org/guidelines/guideline-for-allopurinol-and-hla-b/
amitriptyline and CYP2C19,CYP2D6	https://cpicpgx.org/guidelines/guideline-for-tricyclic-antidepressants-and-cyp2d6-and-cyp2c19/
atazanavir and UGT1A1	https://cpicpgx.org/guidelines/guideline-for-atazanavir-and-ugt1a1/
azathioprine and TPMT	https://cpicpgx.org/guidelines/guideline-for-thiopurines-and-tpmt/
capecitabine and DPYD	https://cpicpgx.org/guidelines/guideline-for-fluoropyrimidines-and-dpyd/
carbamazepine and HLA-B	https://cpicpgx.org/guidelines/guideline-for-carbamazepine-and-hla-b/
citalopram,escitalopram and CYP2C19	https://cpicpgx.org/guidelines/guideline-for-selective-serotonin-reuptake-inhibitors-and-cyp2d6-and-cyp2c19/
clomipramine and CYP2C19,CYP2D6	https://cpicpgx.org/guidelines/guideline-for-tricyclic-antidepressants-and-cyp2d6-and-cyp2c19/
clopidogrel and CYP2C19	https://cpicpgx.org/guidelines/guideline-for-clopidogrel-and-cyp2c19/
codeine and CYP2D6	https://cpicpgx.org/guidelines/guideline-for-codeine-and-cyp2d6/
desipramine and CYP2D6	https://cpicpgx.org/guidelines/guideline-for-tricyclic-antidepressants-and-cyp2d6-and-cyp2c19/
doxepin and CYP2C19,CYP2D6	https://cpicpgx.org/guidelines/guideline-for-tricyclic-antidepressants-and-cyp2d6-and-cyp2c19/
fluorouracil and DPYD	https://cpicpgx.org/guidelines/guideline-for-fluoropyrimidines-and-dpyd/
fluvoxamine and CYP2D6	https://cpicpgx.org/guidelines/guideline-for-selective-serotonin-reuptake-inhibitors-and-cyp2d6-and-cyp2c19/
imipramine and CYP2C19,CYP2D6	https://cpicpgx.org/guidelines/guideline-for-tricyclic-antidepressants-and-cyp2d6-and-cyp2c19/
ivacaftor and CFTR	https://cpicpgx.org/guidelines/guideline-for-ivacaftor-and-cftr/
mercaptopurine and TPMT	https://cpicpgx.org/guidelines/guideline-for-thiopurines-and-tpmt/
nortriptyline and CYP2D6	https://cpicpgx.org/guidelines/guideline-for-tricyclic-antidepressants-and-cyp2d6-and-cyp2c19/
ondansetron and CYP2D6	https://cpicpgx.org/guidelines/guideline-for-ondansetron-and-tropisetron-and-cyp2d6-genotype/
paroxetine and CYP2D6	https://cpicpgx.org/guidelines/guideline-for-selective-serotonin-reuptake-inhibitors-and-cyp2d6-and-cyp2c19/
peginterferon alfa-2a,peginterferon alfa-2b,ribavirin and IFNL3	https://cpicpgx.org/guidelines/guideline-for-peg-interferon-alpha-based-regimens-and-ifnl3/
phenytoin and CYP2C9,HLA-B	https://cpicpgx.org/guidelines/guideline-for-phenytoin-and-cyp2c9-and-hla-b/
rasburicase and G6PD	https://cpicpgx.org/guidelines/guideline-for-rasburicase-and-g6pd/
sertraline and CYP2C19	https://cpicpgx.org/guidelines/guideline-for-selective-serotonin-reuptake-inhibitors-and-cyp2d6-and-cyp2c19/
simvastatin and SLCO1B1	https://cpicpgx.org/guidelines/guideline-for-simvastatin-and-slco1b1/
tacrolimus and CYP3A5	https://cpicpgx.org/guidelines/guideline-for-tacrolimus-and-cyp3a5/
tegafur and DPYD	https://cpicpgx.org/guidelines/guideline-for-fluoropyrimidines-and-dpyd/
thioguanine and TPMT	https://cpicpgx.org/guidelines/guideline-for-thiopurines-and-tpmt/
trimipramine and CYP2C19,CYP2D6	https://cpicpgx.org/guidelines/guideline-for-tricyclic-antidepressants-and-cyp2d6-and-cyp2c19/
tropisetron and CYP2D6	https://cpicpgx.org/guidelines/guideline-for-ondansetron-and-tropisetron-and-cyp2d6-genotype/
voriconazole and CYP2C19	https://cpicpgx.org/guidelines/guideline-for-voriconazole-and-cyp2c19/
warfarin and CYP2C9,CYP4F2,VKORC1	https://cpicpgx.org/guidelines/guideline-for-warfarin-and-cyp2c9-and-vkorc1/
\.
